name: todo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  introduction_screen: ^2.1.0
  intl: ^0.17.0
  flutter_slidable: ^0.6.0
  table_calendar: ^3.0.1
  measure_size: ^2.0.0
  percent_indicator: ^3.0.1
  uuid: ^3.0.4
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_core: ^1.5.0
  adaptive_dialog: ^1.1.0
  cached_network_image: ^3.1.0
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets: 
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
